### ISSUE TITLE
Add new folder -right left cursor issue in Notes section

### ISSUE THREAD

**Issue by henley352** [storybuilder-org/StoryBuilder-2#220] opened 2022-03-16 00:33 UTC
**Describe the bug**
Add new folder -right left cursor issue in Notes section.

**To Reproduce**
1. Go to 'menu bar..'
2. Click on '.add features..'
3. Scroll down to 'new folder....'
4. click on new folder in navigation pane
5.  in content pane, tab to notes section

**Expected behavior**
Cursor is at the start of the text box

**Screenshots**
![image](https://user-images.githubusercontent.com/21226407/158493484-836287dd-dc53-4100-aba6-b9fcab3c97ae.png)

**Additional context**

**Comment by henley352** [comment] 2022-03-16 00:35
another cursor issue new problem
![image](https://user-images.githubusercontent.com/21226407/158494238-8fec64e9-e6bc-4267-be87-12f24e882fe8.png)

**Comment by henley352** [comment] 2022-03-16 00:38
another cursor issue -just keeping here so i can go back and retest these issues 

![image](https://user-images.githubusercontent.com/21226407/158494503-e8ac531e-a6da-4e07-acf7-11bdc8566f7e.png)

**Comment by henley352** [comment] 2022-03-16 00:39
![image](https://user-images.githubusercontent.com/21226407/158494576-d7e05b94-f614-42f8-954b-63e5de83a38a.png)

**Comment by Rarisma** [comment] 2022-03-16 09:06
Duplicate of #195

**Closed by Rarisma** 2022-03-16 09:06 UTC
Labels: bug
