### ISSUE TITLE
Sample Content remains after closing out of Storybuilder

### ISSUE THREAD

**Issue by henley352** [storybuilder-org/StoryBuilder-2#182] opened 2022-02-26 14:02 UTC
**Describe the bug**
I opened Rocky sample last night.  I closed out of SB and opened this morning and Rocky sample still displays with only option as Rocky

**To Reproduce**
1. Go to StoryBuilder Story Explorer View
2. Click on 'Samples'
3. Scroll down to 'Rocky'
4.  Close out of SB using X
5.  Open SB 

**Expected behavior**
Samples display with all options.

Actual Result
Only option is Rocky sample -doesn't reset with all options for samples

![SB_doesn't clear out prior project sample](https://user-images.githubusercontent.com/21226407/155845969-bb044937-f00f-4d94-a5e9-d305da590bc2.PNG)

**Comment by Rarisma** [comment] 2022-02-26 16:13
Duplicate of #181

**Closed by Rarisma** 2022-02-26 16:13 UTC
