### ISSUE TITLE
character - New Role - Typing first letter does not pull up descriptions that start with that letter - user has to scroll to find 

### ISSUE THREAD

**Issue by henley352** [storybuilder-org/StoryBuilder-2#307] opened 2022-05-14 14:48 UTC
**Describe the bug**
Role - Typing first letter does not pull up descriptions that start with that letter - user has to scroll to find 

**To Reproduce**
1. Go to 'new character'
2. Click on 'role'
3.  Type Wra
4.  stays on A
5.User has to scroll

**Expected behavior**
Words beginning with that letter are highlighted

**Screenshots**
![image](https://user-images.githubusercontent.com/21226407/168430301-6a2ff449-3c90-4bea-a33e-f072450fb0de.png)

**Additional context**
[updater.2022-05-14.log](https://github.com/storybuilder-org/StoryBuilder-2/files/8693172/updater.2022-05-14.log)

**Comment by henley352** [comment] 2022-06-11 17:35
this page  - allows user to type first letter to get option 
![image](https://user-images.githubusercontent.com/21226407/173198724-7f2aeb96-e642-4732-a499-64783e620fad.png)

**Comment by Rarisma** [comment] 2022-07-05 19:46
Duplicate of #296

**Closed by Rarisma** 2022-07-05 19:46 UTC
Labels: enhancement
